version: "3.8"

services:
  pitchlake-ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    environment:
      - NODE_ENV=production
      - PORT= ${PORT}
      - NEXT_PUBLIC_VAULT_ADDRESS=${NEXT_PUBLIC_VAULT_ADDRESS}
      - NEXT_PUBLIC_ENVIRONMENT=${NEXT_PUBLIC_ENVIRONMENT}
      - NEXT_PUBLIC_RPC_URL_MAINNET=${NEXT_PUBLIC_RPC_URL_MAINNET}
      - NEXT_PUBLIC_RPC_URL_SEPOLIA=${NEXT_PUBLIC_RPC_URL_SEPOLIA}
      - NEXT_PUBLIC_WS_URL=${NEXT_PUBLIC_WS_URL}
      - FOSSIL_API_KEY=${FOSSIL_API_KEY}
      - FOSSIL_DB_URL=${FOSSIL_DB_URL}
      - ALCHEMY_API_KEY=${ALCHEMY_API_KEY}
      - DEMO_ACCOUNT_ADDRESS=${DEMO_ACCOUNT_ADDRESS}
      - DEMO_PRIVATE_KEY=${DEMO_PRIVATE_KEY}
      - NEXT_PUBLIC_FOSSIL_API_URL=${NEXT_PUBLIC_FOSSIL_API_URL}
      - NEXT_PUBLIC_WS_URL=${NEXT_PUBLIC_WS_URL}
      # ⬇️⬇️⬇️ MANDATORY FOR DEVELOPMENT ENVIRONMENT - NOT NEEDED IN PRODUCTION
      - JUNO_DOCKER_HOST=http://juno_plugin:6060
      - NEXT_PUBLIC_RPC_URL_DEVNET=${NEXT_PUBLIC_RPC_URL_DEVNET}
      - NEXT_PUBLIC_RPC_URL_JUNO_DEVNET=${NEXT_PUBLIC_RPC_URL_JUNO_DEVNET}
