version: '3.8'

services:
  pitchlake-ui:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=3003
      - NEXT_PUBLIC_VAULT_ADDRESS=0xdeadbeef
    ports:
      - "3003:3003"