version: '3.8'

services:
  pitchlake-ui:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=${UI_PORT}
    ports:
      - "${UI_PORT}:${UI_PORT}"
    env_file:
      - .env